config/routes.rb
LetsConnect::Application.routes.draw do
  resources :additional_attributes

  devise_for :users

  resources :users

  root to: 'users#index' 

end

app/models/additional_attribute.rb
class AdditionalAttribute < ActiveRecord::Base
  attr_accessible :attr_class, :name, :attr_type, :value

  SINGLE_VALUED_ATTRIBUTE = ['Integer', 'Float', 'String', 'Date', 'Relationship']
  MULTI_VALUED_ATTRIBUTE = ['Select Box', 'Checkbox', 'Radio Button']

  serialize :value

  has_many :attribute_values

  scope :get_additional_attributes, lambda{|attr_class| where(:attr_class => attr_class)}

  def get_model_names  	
  	ActiveRecord::Base.descendants.map(&:name).sort - [self.class.name]
  end

end

app/models/attribute_value.rb
class AttributeValue < ActiveRecord::Base
  attr_accessible :additional_attribute_id, :owner_id, :value
  belongs_to :additional_attribute
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name, :photo, :address, :work_info

  has_attached_file :photo, :path => ":rails_root/public/system/:attachment/:id/:style/:filename",
      				:url => "/system/:attachment/:id/:style/:filename", 
      				:styles => {:thumb=> "50x50#",
                                :small => "150x150>",
                                :medium => "300x300>",
                                :large => "400x400>"
                               }

  has_many :attribute_values

  has_many :family_members, :class_name => "User"
  has_many :friends, :class_name => "User"
  has_many :business_members, :class_name => "User"
  
  AdditionalAttribute.get_additional_attributes(self.name).each do |attr|
    attr_accessible attr.name 
    define_method(attr.name) do
      attr.attribute_values.where(:owner_id => self.id).first.try(:value)
    end
    define_method("#{attr.name}=") do |value|
      obj = attr.attribute_values.where(:owner_id => self.id).first
      obj.value = value
      obj.save!
    end
  end

end

app/controllers/additional_attributes_controller.rb
class AdditionalAttributesController < ApplicationController
  # GET /additional_attributes
  # GET /additional_attributes.json
  def index
    @additional_attributes = AdditionalAttribute.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @additional_attributes }
    end
  end

  # GET /additional_attributes/1
  # GET /additional_attributes/1.json
  def show
    @additional_attribute = AdditionalAttribute.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @additional_attribute }
    end
  end

  # GET /additional_attributes/new
  # GET /additional_attributes/new.json
  def new
    @additional_attribute = AdditionalAttribute.new
    @models = @additional_attribute.get_model_names
    @attr_type = AdditionalAttribute::SINGLE_VALUED_ATTRIBUTE + AdditionalAttribute::MULTI_VALUED_ATTRIBUTE

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @additional_attribute }
    end
  end

  # GET /additional_attributes/1/edit
  def edit
    @additional_attribute = AdditionalAttribute.find(params[:id])
  end

  # POST /additional_attributes
  # POST /additional_attributes.json
  def create
    params[:additional_attribute][:value] = params[:additional_attribute][:value].split('#')
    @additional_attribute = AdditionalAttribute.new(params[:additional_attribute])

    respond_to do |format|
      if @additional_attribute.save
        format.html { redirect_to @additional_attribute, notice: 'Additional attribute was successfully created.' }
        format.json { render json: @additional_attribute, status: :created, location: @additional_attribute }
      else
        format.html { render action: "new" }
        format.json { render json: @additional_attribute.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /additional_attributes/1
  # PUT /additional_attributes/1.json
  def update
    @additional_attribute = AdditionalAttribute.find(params[:id])

    respond_to do |format|
      if @additional_attribute.update_attributes(params[:additional_attribute])
        format.html { redirect_to @additional_attribute, notice: 'Additional attribute was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @additional_attribute.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /additional_attributes/1
  # DELETE /additional_attributes/1.json
  def destroy
    @additional_attribute = AdditionalAttribute.find(params[:id])
    @additional_attribute.destroy

    respond_to do |format|
      format.html { redirect_to additional_attributes_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  before_filter :authenticate_user!
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  before_filter :get_attrs, :only => [:index, :show, :new, :edit, :update]

  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])
    unless @additional_attrs.blank?
      @additional_attrs.each do |attr|
        attr_value = params[attr.name.to_sym]
        AttributeValue.create!(:additional_attribute_id => attr.id, :owner_id => params[:id], :value => attr_value)
      end
    end

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private 
  def get_attrs
    @additional_attrs = AdditionalAttribute.get_additional_attributes('User')    
  end
end

app/helpers/additional_attributes_helper.rb
module AdditionalAttributesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper

  def get_attr_value(attr, user)
    attr.attribute_values.where(:owner_id => user.id).first.value
  end
    
  def generate_feilds_for_additional_attrs(additional_attrs,f)
  	html_str = ''
  	additional_attrs.each do |attr|
  	  html_str << "<div class='feild'>"
  	  html_str << f.label(attr.name)
  	  html_str << "<br/>"
  	  input_type = get_input_type_for_attr(attr,f)
  	  html_str << input_type
  	  html_str << "</div>"
  	end
  	html_str.html_safe
  end

  def get_input_type_for_attr(attr,f)
  	case attr.attr_type
  	when 'Integer', 'Float', 'String'
  	  f.text_field attr.name
  	when 'Select Box'
  	  'select'  	  
  	when 'Checkbox'
  	  'check_box'
  	when 'Radio Button'
  	  'radio_button'
  	end
  end
	
end

app/views/additional_attributes/_form.html.erb
<%= form_for(@additional_attribute) do |f| %>
  <% if @additional_attribute.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@additional_attribute.errors.count, "error") %> prohibited this additional_attribute from being saved:</h2>

      <ul>
      <% @additional_attribute.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :for_entity %><br />
    <%= f.select :attr_class, @models %>
  </div>
  <div class="field">
    <%= f.label :type %><br />
    <%= f.select :attr_type, @attr_type %>
  </div>
  <div id="attribute_value" class="field" style="display:none">
    <%= f.label :value %> (Enter values separated by #)<br />
    <%= f.text_field :value %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<script type="text/javascript">
  $('#additional_attribute_attr_type').on('change', function(){
    type = $('#additional_attribute_attr_type').val();
    multi_value_attr = "<%= AdditionalAttribute::MULTI_VALUED_ATTRIBUTE.join(',')%>" ;
    multi_value_attr = multi_value_attr.split(',');
    if (jQuery.inArray(type, multi_value_attr) != -1){
      $('#attribute_value').show();
    }else{
      $('#attribute_value').hide();
    }
  });
</script>

app/views/additional_attributes/edit.html.erb
<h1>Editing additional_attribute</h1>

<%= render 'form' %>

<%= link_to 'Show', @additional_attribute %> |
<%= link_to 'Back', additional_attributes_path %>

app/views/additional_attributes/index.html.erb
<h1>Listing additional_attributes</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Attr class</th>
    <th>Type</th>
    <th>Value</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @additional_attributes.each do |additional_attribute| %>
  <tr>
    <td><%= additional_attribute.name %></td>
    <td><%= additional_attribute.attr_class %></td>
    <td><%= additional_attribute.attr_type %></td>
    <td><%= additional_attribute.value.blank? ? '' : additional_attribute.value %></td>
    <td><%= link_to 'Show', additional_attribute %></td>
    <td><%= link_to 'Edit', edit_additional_attribute_path(additional_attribute) %></td>
    <td><%= link_to 'Destroy', additional_attribute, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Additional attribute', new_additional_attribute_path %>

app/views/additional_attributes/new.html.erb
<h1>New additional_attribute</h1>

<%= render 'form' %>

<%= link_to 'Back', additional_attributes_path %>

app/views/additional_attributes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @additional_attribute.name %>
</p>

<p>
  <b>Attr class:</b>
  <%= @additional_attribute.attr_class %>
</p>

<p>
  <b>Type:</b>
  <%= @additional_attribute.attr_type %>
</p>

<% unless @additional_attribute.value.blank? %>
<p>
  <b>Value:</b>
  <%= @additional_attribute.value %>
</p>
<% end %>

<%= link_to 'Edit', edit_additional_attribute_path(@additional_attribute) %> |
<%= link_to 'Back', additional_attributes_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LetsConnect</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div id="user_nav">
    <% if user_signed_in? %>
      Signed in as <%= current_user.email %>. Not you?
      <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
    <% else %>
      <%= link_to "Sign up", new_user_registration_path %> or
      <%= link_to "Sign in", new_user_session_path %>
    <% end %>
  </div>

<%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user,:html=>{:multipart => true}) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  
  <div class="field">
    <%= f.label :photo %><br />
    <%= f.file_field :photo %>
  </div>
  
  <div class="field">
    <%= f.label :email %><br />
    <%= f.email_field :email %>
  </div>
  
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_area :address %>
  </div>
  
  <div class="field">
    <%= f.label :work_info %><br />
    <%= f.text_field :work_info %>
  </div>

  <%= generate_feilds_for_additional_attrs(@additional_attrs,f) %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Address</th>
    <th>Work info</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.email %></td>
    <td><%= user.address %></td>
    <td><%= user.work_info %></td>
    <td><%= link_to 'Show', user %></td>
    <% if current_user == user %>
      <td><%= link_to 'Edit', edit_user_path(user) %></td>
      <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <% end %>
  </tr>
<% end %>
</table>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @user.name %>
</p>
<p>
  <b>Photo:</b>
  <%= image_tag @user.photo.url(:small) %>
</p>
<p>
  <b>Email:</b>
  <%= @user.email %>
</p>

<p>
  <b>Address:</b>
  <%= @user.address %>
</p>

<p>
  <b>Work info:</b>
  <%= @user.work_info %>
</p>

<% @additional_attrs.each do |attr| %>
  <p>
    <b><%= attr.name%>:</b>
    <%= get_attr_value(attr, @user) %>
  </p>
<% end %>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %> |
<%= link_to 'Add New Attribute', new_additional_attribute_path %>